# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ece3a5d65d3638a850bffaf10eb9b6af49d4478911ce8145b40f9b342e088cd24519955db25df3dcf1cac3c008b4bcf9edaba01b0ee1f611a7462d9a54e43d3e

test:
  secret_key_base: f33dbc8b9a699fe5d70b9b14cbf1ea603ea1f4dc5dedd7d30066bf7aac5d7d9a66033bbcf9bf29c2d8535d52db021772bcd138b4ccfbd9a707791a27ac877330

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
